export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_IF_NEEDED = 'FETCH_USERS_IF_NEEDED';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
